import "./globals.css";
import AppProvider from "@/shared/hoc/app-provider/AppProvider";
export const metadata = {
  title: "jusani-portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
